CREATE TABLE IF NOT EXISTS customers (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  state VARCHAR(255) NOT NULL,
  total_spent DECIMAL(10,2) NOT NULL,
  currency VARCHAR(255) NOT NULL,
  last_order_id BIGINT,
  last_order_name VARCHAR(255),
  last_login_at TIMESTAMP,
  note TEXT,
  tags TEXT,
  tax_exempt BOOLEAN NOT NULL,
  verified_email BOOLEAN NOT NULL,
  marketing_opt_in_level VARCHAR(255) NOT NULL,
  multipass_identifier VARCHAR(255),
  email_marketing_consent_state VARCHAR(255) NOT NULL,
  email_marketing_consent_opt_in_level VARCHAR(255) NOT NULL,
  email_marketing_consent_updated_at TIMESTAMP,
  sms_marketing_consent_state VARCHAR(255) NOT NULL,
  sms_marketing_consent_opt_in_level VARCHAR(255) NOT NULL,
  sms_marketing_consent_updated_at TIMESTAMP,
  sms_marketing_consent_collected_from VARCHAR(255),
  metafield_key VARCHAR(255),
  metafield_namespace VARCHAR(255),
  metafield_value TEXT,
  metafield_type VARCHAR(255)
);